#!/usr/bin/env bash
fpmExists=$(which fpm >/dev/null 2>&1 ; echo $?)
if [[ ${fpmExists} -ne 0 ]];then
    echo 'fpm is not installed, exiting.'
    exit 1
fi

if [[ $1 != "local" ]]; then
  cd /build
fi

fpm -s dir -t rpm -C ./slash/ \
    --verbose \
    --name apache-spark \
    --version 2.0.2 \
    --iteration 1 \
    --depends 'jre >= 1.8.0' \
    --after-install 'slash/opt/spark/extras/after-install.sh' \
    --after-remove 'slash/opt/spark/extras/after-remove.sh' \
    --vendor 'sellorm' \
    --license 'Apache V2' \
    --maintainer 'spark@5vcc.com' \
    --url 'https://github.com/sellorm/spark-pkg' \
    --description "Packaged version of Apache Spark" .

# rpm -qpRi --provides --scripts ./apache_spark-2.0.2-1.x86_64.rpm
